"""
Backtesting engine for simulating realistic trade execution from signals.

Consumes a signal dataset (BUY/HOLD/SELL per symbol per date) and a
price dataset, and produces a realistic trade log accounting for
transaction costs and slippage.

This module owns per-symbol trade execution only. Portfolio-level
cash management and capital allocation across symbols belongs to
portfolio_simulator.py.
"""

from __future__ import annotations

import itertools
from dataclasses import asdict, dataclass

import pandas as pd

from config.settings import settings
from src.utils.logger import get_logger

logger = get_logger(__name__)


@dataclass(slots=True)
class Trade:
    """A single completed trade with realistic cost accounting."""

    trade_id: int
    symbol: str
    entry_date: pd.Timestamp
    exit_date: pd.Timestamp
    entry_price: float
    exit_price: float
    position_size: float
    fees: float
    slippage_cost: float
    pnl: float
    return_pct: float


@dataclass(slots=True)
class BacktestResult:
    """Container for all trades generated by a backtest run."""

    trades: list[Trade]
    trades_df: pd.DataFrame


class BacktestingEngine:
    """
    Execute realistic per-symbol trade simulations from model signals.

    Trade IDs are generated by an instance-level counter. They are unique
    within a single BacktestingEngine instance and intentionally reset when
    a new engine instance is created.
    """

    def __init__(
        self,
        capital_per_trade: float | None =None,
        transaction_cost: float | None = None,
        slippage: float | None = None,
    ) -> None:
        """
        Args:
            capital_per_trade:
                Capital allocated to each new position.
                Defaults to
                settings.INITIAL_CAPITAL * settings.MAX_POSITION_SIZE.
            transaction_cost:
                Fractional transaction cost applied per trade leg.
            slippage:
                Fractional adverse execution slippage.
        """
        self.capital_per_trade = capital_per_trade or (
            settings.INITIAL_CAPITAL * settings.MAX_POSITION_SIZE
        )

        self.transaction_cost = (
            transaction_cost
            if transaction_cost is not None
            else settings.TRANSACTION_COST
        )

        self.slippage = (
            slippage if slippage is not None else settings.SLIPPAGE
        )

        self._trade_id_counter = itertools.count(1)

    def run(
        self,
        signals_df: pd.DataFrame,
        prices_df: pd.DataFrame,
    ) -> BacktestResult:
        """
        Run a complete backtest across all symbols.

        Args:
            signals_df:
                Signal dataframe containing BUY/HOLD/SELL signals.

            prices_df:
                Price dataframe used for trade execution.

        Returns:
            BacktestResult containing completed trades.
        """
        if signals_df.empty:
            raise ValueError("signals_df cannot be empty.")

        if prices_df.empty:
            raise ValueError("prices_df cannot be empty.")

        required_signal_cols = {"symbol", "date", "signal"}
        missing = required_signal_cols - set(signals_df.columns)

        if missing:
            raise ValueError(
                f"signals_df missing required columns: {missing}"
            )

        required_price_cols = {"symbol", "date", "close"}
        missing = required_price_cols - set(prices_df.columns)

        if missing:
            raise ValueError(
                f"prices_df missing required columns: {missing}"
            )

        prices = prices_df.copy()

        if "adj_close" in prices.columns:
            prices["execution_price"] = prices["adj_close"].fillna(
                prices["close"]
            )
        else:
            prices["execution_price"] = prices["close"]

        merged = pd.merge(
            signals_df[["symbol", "date", "signal"]],
            prices[["symbol", "date", "execution_price"]],
            on=["symbol", "date"],
            how="inner",
        )

        if merged.empty:
            raise ValueError(
                "No overlapping (symbol, date) rows between "
                "signals_df and prices_df."
            )

        merged = (
            merged.sort_values(["symbol", "date"])
            .reset_index(drop=True)
        )

        logger.info(
            "Running backtest for %d symbols.",
            merged["symbol"].nunique(),
        )

        all_trades: list[Trade] = []

        for symbol, group in merged.groupby("symbol", sort=False):
            all_trades.extend(self._simulate_symbol(symbol, group))

        if not all_trades:
            logger.warning(
                "Backtest produced zero trades across all symbols."
            )

        trades_df = pd.DataFrame(
            [asdict(trade) for trade in all_trades]
        )

        logger.info(
            "Backtest completed with %d trades.",
            len(all_trades),
        )

        return BacktestResult(
            trades=all_trades,
            trades_df=trades_df,
        )

    def _simulate_symbol(
        self,
        symbol: str,
        group: pd.DataFrame,
    ) -> list[Trade]:
        """
        Walk through a single symbol chronologically.

        Opens a position on BUY when flat and closes on SELL when
        holding a position.

        Open positions at the end of the dataset are force-closed
        using the final available price.
        """
        trades: list[Trade] = []

        open_entry_date: pd.Timestamp | None = None
        open_entry_price: float | None = None

        for _, row in group.iterrows():
            if open_entry_date is None and row["signal"] == 1:
                open_entry_date = row["date"]
                open_entry_price = row["execution_price"]

            elif open_entry_date is not None and row["signal"] == -1:
                trades.append(
                    self._build_trade(
                        symbol=symbol,
                        entry_date=open_entry_date,
                        raw_entry_price=open_entry_price,
                        exit_date=row["date"],
                        raw_exit_price=row["execution_price"],
                    )
                )

                open_entry_date = None
                open_entry_price = None

        if open_entry_date is not None:
            last_row = group.iloc[-1]

            logger.warning(
                "Symbol=%s has an open position at end of data "
                "(entry_date=%s). Force-closing at last available "
                "price=%s on date=%s.",
                symbol,
                open_entry_date,
                last_row["execution_price"],
                last_row["date"],
            )

            trades.append(
                self._build_trade(
                    symbol=symbol,
                    entry_date=open_entry_date,
                    raw_entry_price=open_entry_price,
                    exit_date=last_row["date"],
                    raw_exit_price=last_row["execution_price"],
                )
            )

        return trades

    def _build_trade(
        self,
        symbol: str,
        entry_date: pd.Timestamp,
        raw_entry_price: float,
        exit_date: pd.Timestamp,
        raw_exit_price: float,
    ) -> Trade:
        """
        Build a completed trade applying slippage and transaction costs.

        Slippage always works against the trader by increasing the
        effective entry price and decreasing the effective exit price.
        """

        if raw_entry_price <= 0 or raw_exit_price <= 0:
            raise ValueError(
                f"Invalid price for symbol={symbol}: "
                f"entry_price={raw_entry_price}, exit_price={raw_exit_price}. "
                f"Prices must be positive."
            )

        executed_entry_price = raw_entry_price * (1 + self.slippage)
        executed_exit_price = raw_exit_price * (1 - self.slippage)

        position_size = (
            self.capital_per_trade / executed_entry_price
        )

        slippage_cost = (
            (executed_entry_price - raw_entry_price) * position_size
            + (raw_exit_price - executed_exit_price) * position_size
        )

        fees = (
            self.transaction_cost
            * (executed_entry_price + executed_exit_price)
            * position_size
        )

        pnl = (
            (executed_exit_price - executed_entry_price)
            * position_size
            - fees
        )

        return Trade(
            trade_id=next(self._trade_id_counter),
            symbol=symbol,
            entry_date=entry_date,
            exit_date=exit_date,
            entry_price=executed_entry_price,
            exit_price=executed_exit_price,
            position_size=position_size,
            fees=fees,
            slippage_cost=slippage_cost,
            pnl=pnl,
            return_pct=pnl / (executed_entry_price * position_size),
        )