"""Initial_schema

Revision ID: 1a0fc36070d1
Revises: 
Create Date: 2026-05-25 15:46:16.726834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a0fc36070d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_class', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=20), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'exchange', name='uq_assets_symbol_exchange')
    )
    op.create_index(op.f('ix_assets_asset_class'), 'assets', ['asset_class'], unique=False)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index('ix_assets_symbol', 'assets', ['symbol'], unique=False)
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('feature_set_version', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_features_symbol_date')
    )
    op.create_index('ix_features_date', 'features', ['date'], unique=False)
    op.create_index('ix_features_feature_set_version', 'features', ['feature_set_version'], unique=False)
    op.create_index(op.f('ix_features_id'), 'features', ['id'], unique=False)
    op.create_index('ix_features_symbol', 'features', ['symbol'], unique=False)
    op.create_table('portfolio_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolio_metrics_calculated_at', 'portfolio_metrics', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_portfolio_metrics_id'), 'portfolio_metrics', ['id'], unique=False)
    op.create_index('ix_portfolio_metrics_metric', 'portfolio_metrics', ['metric'], unique=False)
    op.create_index('ix_portfolio_metrics_strategy_name', 'portfolio_metrics', ['strategy_name'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_prices_symbol_date')
    )
    op.create_index('ix_prices_date', 'prices', ['date'], unique=False)
    op.create_index(op.f('ix_prices_id'), 'prices', ['id'], unique=False)
    op.create_index('ix_prices_symbol', 'prices', ['symbol'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal', sa.Integer(), nullable=False),
    sa.Column('predicted_return', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_signals_symbol_date')
    )
    op.create_index('ix_signals_date', 'signals', ['date'], unique=False)
    op.create_index(op.f('ix_signals_id'), 'signals', ['id'], unique=False)
    op.create_index('ix_signals_model_version', 'signals', ['model_version'], unique=False)
    op.create_index('ix_signals_symbol', 'signals', ['symbol'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('entry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=False),
    sa.Column('position_size', sa.Float(), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('slippage_cost', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('return_pct', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trades_entry_date', 'trades', ['entry_date'], unique=False)
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index('ix_trades_symbol', 'trades', ['symbol'], unique=False)
    op.create_index('ix_trades_symbol_entry_date', 'trades', ['symbol', 'entry_date'], unique=False)
    op.drop_index(op.f('index_inputs_destination_type_destination_id_source_type'), table_name='inputs')
    op.drop_index(op.f('index_inputs_input_uuid'), table_name='inputs')
    op.drop_table('inputs')
    op.drop_index(op.f('index_metrics_run_uuid'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('index_datasets_dataset_uuid'), table_name='datasets')
    op.drop_index(op.f('index_datasets_experiment_id_dataset_source_type'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('index_trace_request_metadata_request_id'), table_name='trace_request_metadata')
    op.drop_table('trace_request_metadata')
    op.drop_table('experiments')
    op.drop_table('input_tags')
    op.drop_index(op.f('index_params_run_uuid'), table_name='params')
    op.drop_table('params')
    op.drop_table('runs')
    op.drop_table('registered_models')
    op.drop_table('model_versions')
    op.drop_table('model_version_tags')
    op.drop_index(op.f('index_trace_info_experiment_id_timestamp_ms'), table_name='trace_info')
    op.drop_table('trace_info')
    op.drop_table('experiment_tags')
    op.drop_index(op.f('index_trace_tags_request_id'), table_name='trace_tags')
    op.drop_table('trace_tags')
    op.drop_index(op.f('index_tags_run_uuid'), table_name='tags')
    op.drop_table('tags')
    op.drop_table('registered_model_tags')
    op.drop_table('registered_model_aliases')
    op.drop_index(op.f('index_latest_metrics_run_uuid'), table_name='latest_metrics')
    op.drop_table('latest_metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('latest_metrics',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('step', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('is_nan', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('run_uuid', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_uuid'], ['runs.run_uuid'], name=op.f('latest_metrics_run_uuid_fkey')),
    sa.PrimaryKeyConstraint('key', 'run_uuid', name=op.f('latest_metric_pk'))
    )
    op.create_index(op.f('index_latest_metrics_run_uuid'), 'latest_metrics', ['run_uuid'], unique=False)
    op.create_table('registered_model_aliases',
    sa.Column('alias', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['name'], ['registered_models.name'], name=op.f('registered_model_alias_name_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('name', 'alias', name=op.f('registered_model_alias_pk'))
    )
    op.create_table('registered_model_tags',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['name'], ['registered_models.name'], name=op.f('registered_model_tags_name_fkey'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('key', 'name', name=op.f('registered_model_tag_pk'))
    )
    op.create_table('tags',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('run_uuid', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_uuid'], ['runs.run_uuid'], name=op.f('tags_run_uuid_fkey')),
    sa.PrimaryKeyConstraint('key', 'run_uuid', name=op.f('tag_pk'))
    )
    op.create_index(op.f('index_tags_run_uuid'), 'tags', ['run_uuid'], unique=False)
    op.create_table('trace_tags',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=8000), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['trace_info.request_id'], name=op.f('fk_trace_tags_request_id')),
    sa.PrimaryKeyConstraint('key', 'request_id', name=op.f('trace_tag_pk'))
    )
    op.create_index(op.f('index_trace_tags_request_id'), 'trace_tags', ['request_id'], unique=False)
    op.create_table('experiment_tags',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], name=op.f('experiment_tags_experiment_id_fkey')),
    sa.PrimaryKeyConstraint('key', 'experiment_id', name=op.f('experiment_tag_pk'))
    )
    op.create_table('trace_info',
    sa.Column('request_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp_ms', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('execution_time_ms', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], name=op.f('fk_trace_info_experiment_id')),
    sa.PrimaryKeyConstraint('request_id', name=op.f('trace_info_pk'))
    )
    op.create_index(op.f('index_trace_info_experiment_id_timestamp_ms'), 'trace_info', ['experiment_id', 'timestamp_ms'], unique=False)
    op.create_table('model_version_tags',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['name', 'version'], ['model_versions.name', 'model_versions.version'], name=op.f('model_version_tags_name_version_fkey'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('key', 'name', 'version', name=op.f('model_version_tag_pk'))
    )
    op.create_table('model_versions',
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('creation_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_updated_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('current_stage', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('run_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('status_message', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('run_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('storage_location', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['name'], ['registered_models.name'], name=op.f('model_versions_name_fkey'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('name', 'version', name=op.f('model_version_pk'))
    )
    op.create_table('registered_models',
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('creation_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_updated_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name', name=op.f('registered_model_pk'))
    )
    op.create_table('runs',
    sa.Column('run_uuid', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('source_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('source_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('entry_point_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=9), autoincrement=False, nullable=True),
    sa.Column('start_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('end_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('source_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('lifecycle_stage', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('artifact_uri', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deleted_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.CheckConstraint("lifecycle_stage::text = ANY (ARRAY['active'::character varying, 'deleted'::character varying]::text[])", name=op.f('runs_lifecycle_stage')),
    sa.CheckConstraint("source_type::text = ANY (ARRAY['NOTEBOOK'::character varying, 'JOB'::character varying, 'LOCAL'::character varying, 'UNKNOWN'::character varying, 'PROJECT'::character varying]::text[])", name=op.f('source_type')),
    sa.CheckConstraint("status::text = ANY (ARRAY['SCHEDULED'::character varying, 'FAILED'::character varying, 'FINISHED'::character varying, 'RUNNING'::character varying, 'KILLED'::character varying]::text[])", name=op.f('runs_status_check')),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], name=op.f('runs_experiment_id_fkey')),
    sa.PrimaryKeyConstraint('run_uuid', name=op.f('run_pk'))
    )
    op.create_table('params',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=8000), autoincrement=False, nullable=False),
    sa.Column('run_uuid', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_uuid'], ['runs.run_uuid'], name=op.f('params_run_uuid_fkey')),
    sa.PrimaryKeyConstraint('key', 'run_uuid', name=op.f('param_pk'))
    )
    op.create_index(op.f('index_params_run_uuid'), 'params', ['run_uuid'], unique=False)
    op.create_table('input_tags',
    sa.Column('input_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('input_uuid', 'name', name=op.f('input_tags_pk'))
    )
    op.create_table('experiments',
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('artifact_location', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('lifecycle_stage', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('creation_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_update_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.CheckConstraint("lifecycle_stage::text = ANY (ARRAY['active'::character varying, 'deleted'::character varying]::text[])", name=op.f('experiments_lifecycle_stage')),
    sa.PrimaryKeyConstraint('experiment_id', name=op.f('experiment_pk')),
    sa.UniqueConstraint('name', name=op.f('experiments_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('trace_request_metadata',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=8000), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['trace_info.request_id'], name=op.f('fk_trace_request_metadata_request_id')),
    sa.PrimaryKeyConstraint('key', 'request_id', name=op.f('trace_request_metadata_pk'))
    )
    op.create_index(op.f('index_trace_request_metadata_request_id'), 'trace_request_metadata', ['request_id'], unique=False)
    op.create_table('datasets',
    sa.Column('dataset_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('digest', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('dataset_source_type', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('dataset_source', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('dataset_schema', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dataset_profile', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], name=op.f('datasets_experiment_id_fkey')),
    sa.PrimaryKeyConstraint('experiment_id', 'name', 'digest', name=op.f('dataset_pk'))
    )
    op.create_index(op.f('index_datasets_experiment_id_dataset_source_type'), 'datasets', ['experiment_id', 'dataset_source_type'], unique=False)
    op.create_index(op.f('index_datasets_dataset_uuid'), 'datasets', ['dataset_uuid'], unique=False)
    op.create_table('metrics',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('run_uuid', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('step', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=False),
    sa.Column('is_nan', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_uuid'], ['runs.run_uuid'], name=op.f('metrics_run_uuid_fkey')),
    sa.PrimaryKeyConstraint('key', 'timestamp', 'step', 'run_uuid', 'value', 'is_nan', name=op.f('metric_pk'))
    )
    op.create_index(op.f('index_metrics_run_uuid'), 'metrics', ['run_uuid'], unique=False)
    op.create_table('inputs',
    sa.Column('input_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('destination_type', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('destination_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('source_type', 'source_id', 'destination_type', 'destination_id', name=op.f('inputs_pk'))
    )
    op.create_index(op.f('index_inputs_input_uuid'), 'inputs', ['input_uuid'], unique=False)
    op.create_index(op.f('index_inputs_destination_type_destination_id_source_type'), 'inputs', ['destination_type', 'destination_id', 'source_type'], unique=False)
    op.drop_index('ix_trades_symbol_entry_date', table_name='trades')
    op.drop_index('ix_trades_symbol', table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_index('ix_trades_entry_date', table_name='trades')
    op.drop_table('trades')
    op.drop_index('ix_signals_symbol', table_name='signals')
    op.drop_index('ix_signals_model_version', table_name='signals')
    op.drop_index(op.f('ix_signals_id'), table_name='signals')
    op.drop_index('ix_signals_date', table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_prices_symbol', table_name='prices')
    op.drop_index(op.f('ix_prices_id'), table_name='prices')
    op.drop_index('ix_prices_date', table_name='prices')
    op.drop_table('prices')
    op.drop_index('ix_portfolio_metrics_strategy_name', table_name='portfolio_metrics')
    op.drop_index('ix_portfolio_metrics_metric', table_name='portfolio_metrics')
    op.drop_index(op.f('ix_portfolio_metrics_id'), table_name='portfolio_metrics')
    op.drop_index('ix_portfolio_metrics_calculated_at', table_name='portfolio_metrics')
    op.drop_table('portfolio_metrics')
    op.drop_index('ix_features_symbol', table_name='features')
    op.drop_index(op.f('ix_features_id'), table_name='features')
    op.drop_index('ix_features_feature_set_version', table_name='features')
    op.drop_index('ix_features_date', table_name='features')
    op.drop_table('features')
    op.drop_index('ix_assets_symbol', table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_class'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###