"""initial_schema

Revision ID: d74f3932a61b
Revises: 
Create Date: 2026-05-27 12:56:56.867178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd74f3932a61b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_class', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=20), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'exchange', name='uq_assets_symbol_exchange')
    )
    op.create_index(op.f('ix_assets_asset_class'), 'assets', ['asset_class'], unique=False)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index('ix_assets_symbol', 'assets', ['symbol'], unique=False)
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('feature_set_version', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_features_symbol_date')
    )
    op.create_index('ix_features_date', 'features', ['date'], unique=False)
    op.create_index('ix_features_feature_set_version', 'features', ['feature_set_version'], unique=False)
    op.create_index(op.f('ix_features_id'), 'features', ['id'], unique=False)
    op.create_index('ix_features_symbol', 'features', ['symbol'], unique=False)
    op.create_table('portfolio_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolio_metrics_calculated_at', 'portfolio_metrics', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_portfolio_metrics_id'), 'portfolio_metrics', ['id'], unique=False)
    op.create_index('ix_portfolio_metrics_metric', 'portfolio_metrics', ['metric'], unique=False)
    op.create_index('ix_portfolio_metrics_strategy_name', 'portfolio_metrics', ['strategy_name'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_prices_symbol_date')
    )
    op.create_index('ix_prices_date', 'prices', ['date'], unique=False)
    op.create_index(op.f('ix_prices_id'), 'prices', ['id'], unique=False)
    op.create_index('ix_prices_symbol', 'prices', ['symbol'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal', sa.Integer(), nullable=False),
    sa.Column('predicted_return', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_signals_symbol_date')
    )
    op.create_index('ix_signals_date', 'signals', ['date'], unique=False)
    op.create_index(op.f('ix_signals_id'), 'signals', ['id'], unique=False)
    op.create_index('ix_signals_model_version', 'signals', ['model_version'], unique=False)
    op.create_index('ix_signals_symbol', 'signals', ['symbol'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('entry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=False),
    sa.Column('position_size', sa.Float(), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('slippage_cost', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('return_pct', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trades_entry_date', 'trades', ['entry_date'], unique=False)
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index('ix_trades_symbol', 'trades', ['symbol'], unique=False)
    op.create_index('ix_trades_symbol_entry_date', 'trades', ['symbol', 'entry_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trades_symbol_entry_date', table_name='trades')
    op.drop_index('ix_trades_symbol', table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_index('ix_trades_entry_date', table_name='trades')
    op.drop_table('trades')
    op.drop_index('ix_signals_symbol', table_name='signals')
    op.drop_index('ix_signals_model_version', table_name='signals')
    op.drop_index(op.f('ix_signals_id'), table_name='signals')
    op.drop_index('ix_signals_date', table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_prices_symbol', table_name='prices')
    op.drop_index(op.f('ix_prices_id'), table_name='prices')
    op.drop_index('ix_prices_date', table_name='prices')
    op.drop_table('prices')
    op.drop_index('ix_portfolio_metrics_strategy_name', table_name='portfolio_metrics')
    op.drop_index('ix_portfolio_metrics_metric', table_name='portfolio_metrics')
    op.drop_index(op.f('ix_portfolio_metrics_id'), table_name='portfolio_metrics')
    op.drop_index('ix_portfolio_metrics_calculated_at', table_name='portfolio_metrics')
    op.drop_table('portfolio_metrics')
    op.drop_index('ix_features_symbol', table_name='features')
    op.drop_index(op.f('ix_features_id'), table_name='features')
    op.drop_index('ix_features_feature_set_version', table_name='features')
    op.drop_index('ix_features_date', table_name='features')
    op.drop_table('features')
    op.drop_index('ix_assets_symbol', table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_class'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
