"""
Repository for Signal database operations.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import delete, select
from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.orm import Session

from src.database.models.signal import Signal
from src.utils.logger import get_logger

logger = get_logger(__name__)


class SignalRepository:
    """Data access layer for Signal entities."""

    def __init__(self, session: Session) -> None:
        self._session = session

    def upsert(self, data: dict) -> Signal:
        """
        Insert or update a signal record.

        Conflict key:
            (symbol, date)
        """

        stmt = (
            insert(Signal)
            .values(**data)
            .on_conflict_do_update(
                index_elements=["symbol", "date"],
                set_={
                    "signal": data["signal"],
                    "predicted_return": data["predicted_return"],
                    "model_version": data["model_version"],
                },
            )
        )

        self._session.execute(stmt)

        signal = self._session.scalar(
            select(Signal).where(
                Signal.symbol == data["symbol"],
                Signal.date == data["date"],
            )
        )

        if signal is None:
            raise RuntimeError(
                f"Failed to fetch signal after upsert: "
                f"{data['symbol']} {data['date']}"
            )

        logger.info(
            "Upserted signal symbol=%s date=%s model_version=%s",
            data["symbol"],
            data["date"],
            data["model_version"],
        )

        return signal

    def get_by_symbol(
        self,
        symbol: str,
    ) -> list[Signal]:
        """
        Fetch all signals for a symbol.

        Ordered by date ascending.
        """

        stmt = (
            select(Signal)
            .where(
                Signal.symbol == symbol,
            )
            .order_by(
                Signal.date.asc(),
            )
        )

        return list(
            self._session.scalars(stmt)
        )

    def get_by_date_range(
        self,
        symbol: str,
        start_date: datetime,
        end_date: datetime,
    ) -> list[Signal]:
        """
        Fetch signals within a date range.

        Inclusive on both ends.
        Ordered by date ascending.
        """

        stmt = (
            select(Signal)
            .where(
                Signal.symbol == symbol,
                Signal.date >= start_date,
                Signal.date <= end_date,
            )
            .order_by(
                Signal.date.asc(),
            )
        )

        return list(
            self._session.scalars(stmt)
        )

    def get_by_model_version(
        self,
        version: str,
    ) -> list[Signal]:
        """
        Fetch all signals generated by a model version.

        Ordered by symbol then date.
        """

        stmt = (
            select(Signal)
            .where(
                Signal.model_version == version,
            )
            .order_by(
                Signal.symbol.asc(),
                Signal.date.asc(),
            )
        )

        return list(
            self._session.scalars(stmt)
        )

    def bulk_insert(
        self,
        records: list[dict],
    ) -> int:
        """
        Bulk insert signal records.

        Duplicate (symbol, date) rows are ignored.
        """

        if not records:
            return 0

        stmt = (
            insert(Signal)
            .on_conflict_do_nothing(
                index_elements=[
                    "symbol",
                    "date",
                ]
            )
        )

        self._session.execute(
            stmt,
            records,
        )

        logger.info(
            "Bulk inserted %s signal records.",
            len(records),
        )

        return len(records)

    def delete_by_symbol(
        self,
        symbol: str,
    ) -> int:
        """
        Delete all signals for a symbol.
        """

        result = self._session.execute(
            delete(Signal).where(
                Signal.symbol == symbol,
            )
        )

        deleted = result.rowcount or 0

        logger.info(
            "Deleted %s signal rows for symbol=%s",
            deleted,
            symbol,
        )

        return deleted